### ISSUE TITLE
ERROR:root:Error: Made one or multiple attempts, all errored: - invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by shimul-dey-cb** [breez/breez-sdk-liquid#492]
**I am using 
python package Breez Liquid SDK latest one
Network is mainnet and below code**

from breez_sdk_liquid.breez_sdk_liquid import *
import logging
from mnemonic import Mnemonic
mnemo = Mnemonic("english")
words = mnemo.generate(strength=256)

mnemonic = words

config = default_config(LiquidNetwork.MAINNET)

config.working_dir = "mydir"
try:
    connect_request = ConnectRequest(config, mnemonic)
    sdk = connect(connect_request)
    print(sdk)
except Exception as error:
    logging.error(error)
    raise
    
**This shows below error** 

ERROR:root:Error: Made one or multiple attempts, all errored:
        - invalid peer certificate: UnknownIssuer

Traceback (most recent call last):
  File "C:\Users\shimu\OneDrive\Desktop\py-wallet\wallet.py", line 21, in <module>
    sdk = connect(connect_request)
  File "C:\Users\shimu\AppData\Local\Programs\Python\Python39\lib\site-packages\breez_sdk_liquid\breez_sdk_liquid.py", line 6800, in connect
    return _UniffiConverterTypeBindingLiquidSdk.lift(_rust_call_with_error(_UniffiConverterTypeSdkError,_UniffiLib.uniffi_breez_sdk_liquid_bindings_fn_func_connect,
  File "C:\Users\shimu\AppData\Local\Programs\Python\Python39\lib\site-packages\breez_sdk_liquid\breez_sdk_liquid.py", line 283, in _rust_call_with_error
    _uniffi_check_call_status(error_ffi_converter, call_status)
  File "C:\Users\shimu\AppData\Local\Programs\Python\Python39\lib\site-packages\breez_sdk_liquid\breez_sdk_liquid.py", line 294, in _uniffi_check_call_status      
    raise error_ffi_converter.lift(call_status.error_buf)
breez_sdk_liquid.breez_sdk_liquid.SdkError.Generic: Error: Made one or multiple attempts, all errored:
        - invalid peer certificate: UnknownIssuer

**Comment by ok300** [comment]
@shimul-dey-cb can you please try again with our latest v0.5.1 release, then let us know if this still happens?

Quite a few things were fixed in the meantime.

**Comment by danielgranhao** [comment]
Closing this for now. @shimul-dey-cb please re-open if this is still an issue on [0.6.2](https://github.com/breez/breez-sdk-liquid/releases/tag/0.6.2)
